global:
  scrape_interval: 15s

scrape_configs:
# Prometheus
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
# cadvisor
#- job_name: cadvisor
#  scrape_interval: 5s
#  static_configs:
#  - targets:
#    - cadvisor:8080
# node-exporter
- job_name: node-exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - node-exporter:9100
# java jvm
#- job_name: spring-boot
#  scrape_interval: 5s
#  metrics_path: '/actuator/prometheus'
#  static_configs:
#  - targets:
#    - '192.168.57.5:8081'
