apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
    # Prometheus
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    # node-exporter
    - job_name: node-exporter
      scrape_interval: 5s
      static_configs:
      - targets:
        - 192.168.57.5:9100
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-yml
