#创建一个Deployment类型的app(prometheus)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        imagePullPolicy: IfNotPresent
        args: 
          - "--config.file=/etc/prometheus/prometheus.yml"
        #resources:
          #requests:
          #  cpu: "10m"
          #  memory: "30Mi"
          #limits:
          #  cpu: "50m"
          #  memory: "50Mi"
        ports:
        - containerPort: 9090
          name: web
          protocol: TCP
        volumeMounts:
        - mountPath: "/etc/prometheus"
          name: config
        - mountPath: "/prometheus"
          name: data
      volumes:
      - name: config
        configMap:
          name: prometheus-yml
      - name: data
        hostPath: 
        nfs:
          server: nfs.server.com #NFS服务器IP
          path: /prometheus    #NFS共享目录
          readOnly: false      #可选，默认可读写
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - name: web
    protocol: TCP
    port: 9090         #service对外端口
    targetPort: 9090   #容器端口
    nodePort: 30090    #nodeport
  selector:
    app: prometheus
  type: NodePort
